-- Adventure module: "Dungeon of Doom" — a 3-level, 64x64-per-level dungeon
-- crawl. Every level's entrance sits at the bottom of the map and its exit
-- (a transition POI) sits at the top, matching the brief that the player
-- always fights their way from south to north. Levels 2 and 3 also carry a
-- second transition POI right on their own entrance tile, sending the
-- player back down to the previous level's own exit tile (via the
-- transition payload's optional targetX/targetY, see app/wires/default.bx's
-- _checkMapTransition()/_enterMap()) rather than dropping them back at that
-- level's entrance — so the dungeon can be retraced without rewalking it.
-- Every room bigger than 4x4 (interior,
-- door/entrance room excluded) gets exactly one "spawn" POI with a single
-- level-appropriate random monster. The final level's throne room swaps its
-- spawn for a single named boss (an Ettin, CR 4) instead of a random
-- monster, via a "specific" monsterMode spawn POI.
--
-- row_data lines are LF-separated RLE rows ("count:symbol,..."), one line
-- per grid row within the chunk, decoded against tile_legend by
-- MapService.bx's _decodeChunk()/_decodeRLE(). Chunk (chunk_x, chunk_y) are
-- 0-based; chunk_size 32 means chunk (0,0) covers columns 1-32/rows 1-32,
-- chunk (1,0) covers columns 33-64/rows 1-32, etc. Generated by
-- gen_dungeon.py (see scratchpad) and reviewed/pasted in verbatim.

USE gameserver;
SET NAMES utf8mb4;

INSERT INTO adventure_modules (slug, name, description, version)
VALUES (
    'dungeon-of-doom',
    'Dungeon of Doom',
    'A three-level dungeon crawl: fight north from the entrance hall, through the sunken crypts, to the throne room where the Ettin who rules the dungeon awaits.',
    '1.0.0'
);
SET @doom_module_id = LAST_INSERT_ID();


-- ==================== Level 1: The Entrance Hall ====================
INSERT INTO adventure_maps (
    module_id, slug, name, width, height, chunk_size, tile_legend,
    player_spawn_x, player_spawn_y, opponent_spawn_x, opponent_spawn_y, is_entry
) VALUES (
    @doom_module_id, 'entrance-hall', 'The Entrance Hall', 64, 64, 32,
    '{"#":{"tile":"wall","decoration":""},".":{"tile":"floor","decoration":""},"^":{"tile":"wall","decoration":"torch"},"O":{"tile":"wall","decoration":"pillar"},"D":{"tile":"floor","decoration":"door"},"x":{"tile":"floor","decoration":"spikes"},"c":{"tile":"floor","decoration":"chest"},"b":{"tile":"floor","decoration":"rubble"},"n":{"tile":"wall","decoration":"banner"},"y":{"tile":"floor","decoration":"crystal"}}',
    32, 60, 32, 3, 1
);
SET @doom_map_1_id = LAST_INSERT_ID();

INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_1_id, 0, 0, '32:#\n31:#,1:^\n27:#,5:.\n3:#,7:.,17:#,5:.\n3:#,7:.,17:#,5:.\n3:#,29:.\n3:#,7:.,17:#,5:.\n27:#,5:.\n27:#,5:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n18:#,9:.,4:#,1:.\n18:#,9:.,5:#\n18:#,14:.\n18:#,9:.,5:#\n2:#,8:.,8:#,9:.,5:#\n2:#,8:.,8:#,9:.,5:#\n2:#,8:.,12:#,1:.,9:#\n2:#,21:.,9:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_1_id, 1, 0, '32:#\n32:#\n4:.,28:#\n4:.,28:#\n4:.,28:#\n4:.,28:#\n4:.,28:#\n4:.,28:#\n4:.,28:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n20:#,1:^,11:#\n16:#,10:.,6:#\n16:#,10:.,6:#\n16:#,10:.,6:#\n16:#,10:.,6:#\n8:.,8:#,10:.,6:#\n8:.,8:#,10:.,6:#\n26:.,6:#\n8:.,15:#,1:.,8:#\n8:.,15:#,1:.,8:#\n3:#,1:.,19:#,1:.,8:#\n4:.,19:#,1:.,8:#\n20:#,7:.,5:#\n20:#,7:.,5:#\n20:#,7:.,5:#\n20:#,7:.,5:#\n20:#,7:.,5:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_1_id, 0, 1, '2:#,8:.,22:#\n2:#,8:.,22:#\n2:#,8:.,22:#\n5:#,1:.,26:#\n5:#,1:.,26:#\n5:#,1:.,26:#\n5:#,1:.,26:#\n5:#,1:.,26:#\n5:#,1:.,26:#\n5:#,1:.,26:#\n5:#,1:.,26:#\n5:#,1:.,26:#\n5:#,1:.,25:#,1:.\n5:#,1:.,4:#,1:^,20:#,1:.\n5:#,1:.,3:#,4:.,18:#,1:.\n5:#,8:.,18:#,1:.\n9:#,4:.,18:#,1:.\n9:#,4:.,19:#\n10:#,1:.,21:#\n10:#,1:.,21:#\n10:#,1:.,21:#\n10:#,1:.,4:#,6:.,10:#,1:^\n10:#,1:.,4:#,6:.,5:#,6:.\n10:#,1:.,4:#,6:.,5:#,6:.\n10:#,11:.,5:#,6:.\n15:#,17:.\n15:#,6:.,5:#,6:.\n15:#,6:.,5:#,6:.\n26:#,6:.\n32:#\n32:#\n32:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_1_id, 1, 1, '20:#,7:.,5:#\n20:#,7:.,5:#\n20:#,7:.,5:#\n20:#,7:.,5:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n1:.,31:#\n1:.,31:#\n1:.,31:#\n1:.,31:#\n1:.,31:#\n5:.,27:#\n5:.,27:#\n5:.,27:#\n5:.,27:#\n5:.,27:#\n5:.,27:#\n5:.,27:#\n32:#\n32:#\n32:#');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_1_id, 32, 6, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_1_id, 53, 20, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_1_id, 6, 32, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_1_id, 18, 57, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_1_id, 56, 32, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_1_id, 36, 23, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_1_id, 23, 27, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_1_id, 32, 3, 'transition', '{"targetModule": "dungeon-of-doom", "targetMap": "sunken-crypts"}');

-- ==================== Level 2: The Sunken Crypts ====================
INSERT INTO adventure_maps (
    module_id, slug, name, width, height, chunk_size, tile_legend,
    player_spawn_x, player_spawn_y, opponent_spawn_x, opponent_spawn_y, is_entry
) VALUES (
    @doom_module_id, 'sunken-crypts', 'The Sunken Crypts', 64, 64, 32,
    '{"#":{"tile":"wall","decoration":""},".":{"tile":"floor","decoration":""},"^":{"tile":"wall","decoration":"torch"},"O":{"tile":"wall","decoration":"pillar"},"D":{"tile":"floor","decoration":"door"},"x":{"tile":"floor","decoration":"spikes"},"c":{"tile":"floor","decoration":"chest"},"b":{"tile":"floor","decoration":"rubble"},"n":{"tile":"wall","decoration":"banner"},"y":{"tile":"floor","decoration":"crystal"}}',
    32, 60, 32, 3, 0
);
SET @doom_map_2_id = LAST_INSERT_ID();

INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_2_id, 0, 0, '32:#\n31:#,1:^\n27:#,5:.\n27:#,5:.\n27:#,5:.\n27:#,5:.\n27:#,5:.\n27:#,5:.\n27:#,5:.\n31:#,1:.\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n20:#,1:^,11:#\n17:#,8:.,7:#\n17:#,8:.,7:#\n17:#,8:.,7:#\n17:#,15:.\n17:#,8:.,7:#\n11:#,1:^,5:#,8:.,7:#\n8:#,7:.,2:#,8:.,7:#\n8:#,7:.,5:#,1:.,11:#\n8:#,7:.,5:#,1:.,11:#\n8:#,13:.,11:#\n8:#,7:.,17:#\n8:#,7:.,17:#\n8:#,7:.,17:#\n11:#,1:.,20:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_2_id, 1, 0, '32:#\n32:#\n4:.,28:#\n4:.,28:#\n4:.,28:#\n4:.,28:#\n4:.,28:#\n4:.,5:#,8:.,15:#\n4:.,5:#,8:.,15:#\n17:.,15:#\n9:#,8:.,15:#\n9:#,8:.,15:#\n12:#,1:.,19:#\n12:#,1:.,19:#\n12:#,1:.,19:#\n12:#,1:.,19:#\n12:#,1:.,19:#\n9:.,3:#,1:.,19:#\n13:.,19:#\n9:.,23:#\n9:.,23:#\n5:.,27:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n21:#,7:.,4:#\n21:#,7:.,4:#\n21:#,7:.,4:#\n21:#,7:.,4:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_2_id, 0, 1, '11:#,1:.,20:#\n11:#,1:.,20:#\n11:#,1:.,20:#\n11:#,1:.,20:#\n11:#,1:.,20:#\n11:#,10:.,6:#,5:.\n11:#,10:.,6:#,5:.\n11:#,10:.,6:#,5:.\n12:#,20:.\n12:#,9:.,6:#,5:.\n12:#,9:.,6:#,5:.\n13:#,1:.,13:#,5:.\n13:#,1:.,18:#\n13:#,1:.,18:#\n13:#,1:.,18:#\n13:#,1:.,18:#\n13:#,1:.,18:#\n13:#,1:.,18:#\n13:#,1:.,18:#\n13:#,1:.,18:#\n10:#,7:.,15:#\n10:#,7:.,14:#,1:^\n10:#,7:.,9:#,6:.\n10:#,7:.,9:#,6:.\n10:#,7:.,9:#,6:.\n10:#,7:.,9:#,6:.\n26:#,6:.\n26:#,6:.\n26:#,6:.\n32:#\n32:#\n32:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_2_id, 1, 1, '21:#,7:.,4:#\n21:#,7:.,4:#\n21:#,7:.,4:#\n21:#,7:.,4:#\n24:#,1:.,7:#\n1:.,23:#,1:.,7:#\n1:.,23:#,1:.,7:#\n1:.,23:#,1:.,7:#\n1:.,9:#,1:^,13:#,1:.,7:#\n1:.,6:#,8:.,9:#,1:.,7:#\n1:.,6:#,8:.,9:#,1:.,7:#\n25:.,7:#\n7:#,8:.,17:#\n7:#,8:.,17:#\n7:#,8:.,17:#\n10:#,1:.,21:#\n10:#,1:.,21:#\n10:#,1:.,21:#\n10:#,1:.,21:#\n10:#,1:.,21:#\n10:#,1:.,21:#\n10:#,1:.,21:#\n5:.,5:#,1:.,21:#\n5:.,5:#,1:.,21:#\n5:.,3:#,5:.,19:#\n13:.,19:#\n5:.,3:#,5:.,19:#\n5:.,3:#,5:.,19:#\n5:.,27:#\n32:#\n32:#\n32:#');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 32, 6, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 14, 55, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 12, 28, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 21, 22, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 43, 44, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 45, 10, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 17, 40, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 57, 32, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 30, 41, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 32, 3, 'transition', '{"targetModule": "dungeon-of-doom", "targetMap": "throne-of-doom"}');
-- Return trip: stepping back onto this level's own entrance tile sends the player back down to the previous level's entrance.
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_2_id, 32, 60, 'transition', '{"targetModule": "dungeon-of-doom", "targetMap": "entrance-hall", "targetX": 32, "targetY": 3}');

-- ==================== Level 3: The Throne of Doom ====================
INSERT INTO adventure_maps (
    module_id, slug, name, width, height, chunk_size, tile_legend,
    player_spawn_x, player_spawn_y, opponent_spawn_x, opponent_spawn_y, is_entry
) VALUES (
    @doom_module_id, 'throne-of-doom', 'The Throne of Doom', 64, 64, 32,
    '{"#":{"tile":"wall","decoration":""},".":{"tile":"floor","decoration":""},"^":{"tile":"wall","decoration":"torch"},"O":{"tile":"wall","decoration":"pillar"},"D":{"tile":"floor","decoration":"door"},"x":{"tile":"floor","decoration":"spikes"},"c":{"tile":"floor","decoration":"chest"},"b":{"tile":"floor","decoration":"rubble"},"n":{"tile":"wall","decoration":"banner"},"y":{"tile":"floor","decoration":"crystal"}}',
    32, 60, 32, 3, 0
);
SET @doom_map_3_id = LAST_INSERT_ID();

INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_3_id, 0, 0, '32:#\n31:#,1:^\n23:#,9:.\n23:#,9:.\n23:#,9:.\n23:#,9:.\n23:#,9:.\n23:#,9:.\n23:#,9:.\n23:#,9:.\n23:#,9:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n31:#,1:.\n30:#,1:^,1:.\n26:#,6:.\n26:#,6:.\n26:#,6:.\n26:#,6:.\n26:#,6:.\n26:#,6:.\n26:#,6:.\n6:#,1:^,19:#,6:.\n4:#,5:.,17:#,6:.\n4:#,5:.,21:#,1:.,1:#\n4:#,5:.,21:#,1:.,1:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_3_id, 1, 0, '32:#\n32:#\n8:.,24:#\n8:.,24:#\n8:.,24:#\n8:.,24:#\n8:.,24:#\n8:.,24:#\n8:.,24:#\n8:.,24:#\n8:.,24:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n32:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n3:.,29:#\n32:#\n32:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_3_id, 0, 1, '4:#,5:.,21:#,1:.,1:#\n4:#,5:.,21:#,1:.,1:#\n4:#,5:.,21:#,1:.,1:#\n4:#,5:.,21:#,1:.,1:#\n4:#,5:.,21:#,2:.\n4:#,5:.,23:#\n6:#,1:.,25:#\n6:#,1:.,25:#\n6:#,1:.,10:#,9:.,6:#\n6:#,1:.,10:#,9:.,6:#\n6:#,20:.,6:#\n6:#,1:.,10:#,9:.,6:#\n4:#,5:.,8:#,9:.,6:#\n4:#,5:.,12:#,1:.,10:#\n4:#,5:.,12:#,1:.,10:#\n4:#,5:.,12:#,1:.,10:#\n4:#,5:.,12:#,1:.,10:#\n4:#,5:.,12:#,1:.,10:#\n4:#,5:.,12:#,1:.,10:#\n4:#,5:.,12:#,1:.,10:#\n4:#,5:.,12:#,1:.,10:#\n21:#,1:.,9:#,1:^\n21:#,1:.,4:#,6:.\n21:#,1:.,4:#,6:.\n21:#,1:.,4:#,6:.\n21:#,11:.\n26:#,6:.\n26:#,6:.\n26:#,6:.\n32:#\n32:#\n32:#');
INSERT INTO adventure_map_chunks (map_id, chunk_x, chunk_y, row_data) VALUES (@doom_map_3_id, 1, 1, '32:#\n32:#\n12:#,1:^,19:#\n7:#,11:.,14:#\n18:.,14:#\n7:#,11:.,14:#\n7:#,11:.,14:#\n12:#,1:.,19:#\n12:#,1:.,19:#\n12:#,1:.,19:#\n12:#,1:.,19:#\n12:#,1:.,19:#\n12:#,1:.,4:#,4:.,11:#\n12:#,1:.,4:#,4:.,11:#\n12:#,1:.,4:#,4:.,11:#\n12:#,9:.,11:#\n9:#,1:^,7:#,4:.,11:#\n8:#,4:.,5:#,4:.,11:#\n8:#,4:.,5:#,4:.,11:#\n8:#,11:.,13:#\n8:#,4:.,20:#\n8:#,4:.,20:#\n5:.,4:#,1:.,22:#\n5:.,4:#,1:.,22:#\n5:.,4:#,1:.,22:#\n10:.,22:#\n5:.,27:#\n5:.,27:#\n5:.,27:#\n32:#\n32:#\n32:#');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_3_id, 7, 34, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_3_id, 31, 26, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_3_id, 22, 43, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_3_id, 7, 49, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "random", "monsterName": ""}');
-- Final boss: a lone Ettin (CR 4, 85 HP, two-attack multiattack) guarding the throne room.
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_3_id, 32, 7, 'spawn', '{"countMode": "fixed", "count": 1, "countMin": 1, "countMax": 1, "monsterMode": "specific", "monsterName": "Ettin"}');
-- Return trip: stepping back onto this level's own entrance tile sends the player back down to the previous level's entrance.
INSERT INTO adventure_map_pois (map_id, x, y, poi_type, payload) VALUES (@doom_map_3_id, 32, 60, 'transition', '{"targetModule": "dungeon-of-doom", "targetMap": "sunken-crypts", "targetX": 32, "targetY": 3}');
