-- Auto-generated by resources/database/import_legacy_srd.py. Do not edit by hand.
USE gameserver;
SET NAMES utf8mb4;

-- species --------------------------------------------------------------
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Dwarf', 'Medium', 25, 60, 0, 0, 2, 0, 0, 0, 0, 0, 'Common, Dwarvish', 0, 'Poison', 'Your dwarf character has an assortment of inborn abilities, part and parcel of dwarven nature.

Age: Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.

Alignment: Most dwarves are lawful, believing firmly in the benefits of a well-ordered society. They tend toward good as well, with a strong sense of fair play and a belief that everyone deserves to share in the benefits of a just order.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Darkvision', 'Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Dwarven Resilience', 'You have advantage on saving throws against poison, and you have resistance against poison damage.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 3, 'Dwarven Combat Training', 'You have proficiency with the battleaxe, handaxe, light hammer, and warhammer.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 4, 'Tool Proficiency', 'You gain proficiency with the artisan’s tools of your choice: smith’s tools, brewer’s supplies, or mason’s tools.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 5, 'Stonecunning', 'Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus.');
SET @species_parent = @species_id;
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (@species_parent, 'Hill Dwarf', NULL, NULL, NULL, 0, 0, 0, 0, 1, 0, 0, 0, NULL, 0, NULL, 'As a hill dwarf, you have keen senses, deep intuition, and remarkable resilience.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Dwarven Toughness', 'Your hit point maximum increases by 1, and it increases by 1 every time you gain a level.');
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Elf', 'Medium', 30, 60, 0, 2, 0, 0, 0, 0, 0, 0, 'Common, Elvish', 0, NULL, 'Your elf character has a variety of natural abilities, the result of thousands of years of elven refinement.

Age: Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old.

Alignment: Elves love freedom, variety, and self- expression, so they lean strongly toward the gentler aspects of chaos. They value and protect others’ freedom as well as their own, and they are more often good than not. The drow are an exception; their exile has made them vicious and dangerous. Drow are more often evil than not.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Darkvision', 'Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Keen Senses', 'You have proficiency in the Perception skill.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 3, 'Fey Ancestry', 'You have advantage on saving throws against being charmed, and magic can’t put you to sleep.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 4, 'Trance', 'Elves don’t need to sleep. Instead, they meditate deeply, remaining semiconscious, for 4 hours a day. (The Common word for such meditation is “trance.”) While meditating, you can dream after a fashion; such dreams are actually mental exercises that have become reflexive through years of practice.

After resting in this way, you gain the same benefit that a human does from 8 hours of sleep.');
SET @species_parent = @species_id;
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (@species_parent, 'High Elf', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 0, NULL, 'As a high elf, you have a keen mind and a mastery of at least the basics of magic. In many fantasy gaming worlds, there are two kinds of high elves. One type is haughty and reclusive, believing themselves to be superior to non-elves and even other elves. The other type is more common and more friendly, and often encountered among humans and other races.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Elf Weapon Training', 'You have proficiency with the longsword, shortsword, shortbow, and longbow.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Cantrip', 'You know one cantrip of your choice from the wizard spell list. Intelligence is your spellcasting ability for it.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 3, 'Extra Language', 'You can speak, read, and write one extra language of your choice.');
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Halfling', 'Small', 25, NULL, 0, 2, 0, 0, 0, 0, 0, 0, 'Common, Halfling', 0, NULL, 'Your halfling character has a number of traits in common with all other halflings.

Age: A halfling reaches adulthood at the age of 20 and generally lives into the middle of his or her second century.

Alignment: Most halflings are lawful good. As a rule, they are good-hearted and kind, hate to see others in pain, and have no tolerance for oppression. They are also very orderly and traditional, leaning heavily on the support of their community and the comfort of their old ways.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Lucky', 'When you roll a 1 on the d20 for an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Brave', 'You have advantage on saving throws against being frightened.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 3, 'Halfling Nimbleness', 'You can move through the space of any creature that is of a size larger than yours.');
SET @species_parent = @species_id;
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (@species_parent, 'Lightfoot', NULL, NULL, NULL, 0, 0, 0, 0, 0, 1, 0, 0, NULL, 0, NULL, 'As a lightfoot halfling, you can easily hide from notice, even using other people as cover. You’re inclined to be affable and get along well with others.

Lightfoots are more prone to wanderlust than other halflings, and often dwell alongside other races or take up a nomadic life.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Naturally Stealthy', 'You can attempt to hide even when you are obscured only by a creature that is at least one size larger than you.');
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Human', 'Medium', 30, NULL, 1, 1, 1, 1, 1, 1, 0, 0, 'Common', 1, NULL, 'It’s hard to make generalizations about humans, but your human character has these traits.

Age: Humans reach adulthood in their late teens and live less than a century.

Alignment: Humans tend toward no particular alignment. The best and the worst are found among them.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Dragonborn', 'Medium', 30, NULL, 2, 0, 0, 0, 0, 1, 0, 0, 'Common, Draconic', 0, NULL, 'Your draconic heritage manifests in a variety of traits you share with other dragonborn.

Age: Young dragonborn grow quickly. They walk hours after hatching, attain the size and development of a 10-year-old human child by the age of 3, and reach adulthood by 15. They live to be around 80.

Alignment: Dragonborn tend to extremes, making a conscious choice for one side or the other in the cosmic war between good and evil. Most dragonborn are good, but those who side with evil can be terrible villains.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Draconic Ancestry', 'Black — **Damage Type**: Acid; **Breath Weapon**: 5 by 30 ft. line (Dex. save)
Blue — **Damage Type**: Lightning; **Breath Weapon**: 5 by 30 ft. line (Dex. save)
Brass — **Damage Type**: Fire; **Breath Weapon**: 5 by 30 ft. line (Dex. save)
Bronze — **Damage Type**: Lightning; **Breath Weapon**: 5 by 30 ft. line (Dex. save)
Copper — **Damage Type**: Acid; **Breath Weapon**: 5 by 30 ft. line (Dex. save)
Gold — **Damage Type**: Fire; **Breath Weapon**: 15 ft. cone (Dex. save)
Green — **Damage Type**: Poison; **Breath Weapon**: 15 ft. cone (Con. save)
Red — **Damage Type**: Fire; **Breath Weapon**: 15 ft. cone (Dex. save)
Silver — **Damage Type**: Cold; **Breath Weapon**: 15 ft. cone (Con. save)
White — **Damage Type**: Cold; **Breath Weapon**: 15 ft. cone (Con. save)

You have draconic ancestry. Choose one type of dragon from the Draconic Ancestry table. Your breath weapon and damage resistance are determined by the dragon type, as shown in the table.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Breath Weapon', 'You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation.

When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level, and 5d6 at 16th level.

After you use your breath weapon, you can’t use it again until you complete a short or long rest.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 3, 'Damage Resistance', 'You have resistance to the damage type associated with your draconic ancestry.');
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Gnome', 'Small', 25, 60, 0, 0, 0, 2, 0, 0, 0, 0, 'Common, Gnomish', 0, NULL, 'Your gnome character has certain characteristics in common with all other gnomes.

Age: Gnomes mature at the same rate humans do, and most are expected to settle down into an adult life by around age 40. They can live 350 to almost 500 years.

Alignment: Gnomes are most often good. Those who tend toward law are sages, engineers, researchers, scholars, investigators, or inventors. Those who tend toward chaos are minstrels, tricksters, wanderers, or fanciful jewelers. Gnomes are good-hearted, and even the tricksters among them are more playful than vicious.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Darkvision', 'Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Gnome Cunning', 'You have advantage on all Intelligence, Wisdom, and Charisma saving throws against magic.');
SET @species_parent = @species_id;
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (@species_parent, 'Rock Gnome', NULL, NULL, NULL, 0, 0, 1, 0, 0, 0, 0, 0, NULL, 0, NULL, 'As a rock gnome, you have a natural inventiveness and hardiness beyond that of other gnomes.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Artificer’s Lore', 'Whenever you make an Intelligence (History) check related to magic items, alchemical objects, or technological devices, you can add twice your proficiency bonus, instead of any proficiency bonus you normally apply.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Tinker', 'You have proficiency with artisan’s tools (tinker’s tools). Using those tools, you can spend 1 hour and 10 gp worth of materials to construct a Tiny clockwork device (AC 5, 1 hp). The device ceases to function after 24 hours (unless you spend 1 hour repairing it to keep the device functioning), or when you use your action to dismantle it; at that time, you can reclaim the materials used to create it. You can have up to three such devices active at a time.

When you create a device, choose one of the following options:

*Clockwork Toy.* This toy is a clockwork animal, monster, or person, such as a frog, mouse, bird, dragon, or soldier. When placed on the ground, the toy moves 5 feet across the ground on each of your turns in a random direction. It makes noises as appropriate to the creature it represents.
*Fire Starter.* The device produces a miniature flame, which you can use to light a candle, torch, or campfire. Using the device requires your action.
*Music Box.* When opened, this music box plays a single song at a moderate volume. The box stops playing when it reaches the song’s end or when it is closed.');
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Half-Elf', 'Medium', 30, 60, 0, 0, 0, 0, 0, 2, 2, 1, 'Common, Elvish', 1, NULL, 'Your half-elf character has some qualities in common with elves and some that are unique to half-elves.

Age: Half-elves mature at the same rate humans do and reach adulthood around the age of 20. They live much longer than humans, however, often exceeding 180 years.

Alignment: Half-elves share the chaotic bent of their elven heritage. They value both personal freedom and creative expression, demonstrating neither love of leaders nor desire for followers. They chafe at rules, resent others’ demands, and sometimes prove unreliable, or at least unpredictable.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Darkvision', 'Thanks to your elf blood, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Fey Ancestry', 'You have advantage on saving throws against being charmed, and magic can’t put you to sleep.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 3, 'Skill Versatility', 'You gain proficiency in two skills of your choice.');
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Half-Orc', 'Medium', 30, 60, 2, 0, 1, 0, 0, 0, 0, 0, 'Common, Orc', 0, NULL, 'Your half-orc character has certain traits deriving from your orc ancestry.

Age: Half-orcs mature a little faster than humans, reaching adulthood around age 14. They age noticeably faster and rarely live longer than 75 years.

Alignment: Half-orcs inherit a tendency toward chaos from their orc parents and are not strongly inclined toward good. Half-orcs raised among orcs and willing to live out their lives among them are usually evil.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Darkvision', 'Thanks to your orc blood, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Menacing', 'You gain proficiency in the Intimidation skill.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 3, 'Relentless Endurance', 'When you are reduced to 0 hit points but not killed outright, you can drop to 1 hit point instead. You can’t use this feature again until you finish a long rest.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 4, 'Savage Attacks', 'When you score a critical hit with a melee weapon attack, you can roll one of the weapon’s damage dice one additional time and add it to the extra damage of the critical hit.');
INSERT INTO species (parent_species_id, name, size, speed, darkvision, str_bonus, dex_bonus, con_bonus, int_bonus, wis_bonus, cha_bonus, choice_ability_count, choice_ability_bonus, languages, bonus_language_choice, resistances, description) VALUES (NULL, 'Tiefling', 'Medium', 30, 60, 0, 0, 0, 1, 0, 2, 0, 0, 'Common, Infernal', 0, 'Fire', 'Tieflings share certain racial traits as a result of their infernal descent.

Age: Tieflings mature at the same rate as humans but live a few years longer.

Alignment: Tieflings might not have an innate tendency toward evil, but many of them end up there. Evil or not, an independent nature inclines many tieflings toward a chaotic alignment.');
SET @species_id = LAST_INSERT_ID();
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 1, 'Darkvision', 'Thanks to your infernal heritage, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 2, 'Hellish Resistance', 'You have resistance to fire damage.');
INSERT INTO species_traits (species_id, sort_order, name, description) VALUES (@species_id, 3, 'Infernal Legacy', 'You know the *thaumaturgy* cantrip. When you reach 3rd level, you can cast the *hellish rebuke* spell as a 2nd-level spell once with this trait and regain the ability to do so when you finish a long rest. When you reach 5th level, you can cast the *darkness* spell once with this trait and regain the ability to do so when you finish a long rest. Charisma is your spellcasting ability for these spells.');

-- conditions ------------------------------------------------------------
INSERT INTO conditions (name, description) VALUES ('Blinded', 'A blinded creature can’t see and automatically fails any ability check that requires sight.

Attack rolls against the creature have advantage, and the creature’s attack rolls have disadvantage.');
INSERT INTO conditions (name, description) VALUES ('Charmed', 'A charmed creature can’t attack the charmer or target the charmer with harmful abilities or magical effects.

The charmer has advantage on any ability check to interact socially with the creature.');
INSERT INTO conditions (name, description) VALUES ('Deafened', 'A deafened creature can’t hear and automatically fails any ability check that requires hearing.');
INSERT INTO conditions (name, description) VALUES ('Exhaustion', 'Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect’s description.

1: Disadvantage on ability checks
2: Speed halved
3: Disadvantage on attack rolls and saving throws
4: Hit point maximum halved
5: Speed reduced to 0
6: Death

If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect’s description.

A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.

An effect that removes exhaustion reduces its level as specified in the effect’s description, with all exhaustion effects ending if a creature’s exhaustion level is reduced below 1.

Finishing a long rest reduces a creature’s exhaustion level by 1, provided that the creature has also ingested some food and drink.');
INSERT INTO conditions (name, description) VALUES ('Frightened', 'A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.

The creature can’t willingly move closer to the source of its fear.');
INSERT INTO conditions (name, description) VALUES ('Grappled', 'A grappled creature’s speed becomes 0, and it can’t benefit from any bonus to its speed.

The condition ends if the grappler is incapacitated (see the condition).

The condition also ends if an effect removes the grappled creature from the reach of the grappler or grappling effect, such as when a creature is hurled away by the *thunder-wave* spell.');
INSERT INTO conditions (name, description) VALUES ('Incapacitated', 'An incapacitated creature can’t take actions or reactions.');
INSERT INTO conditions (name, description) VALUES ('Invisible', 'An invisible creature is impossible to see without the aid of magic or a special sense. For the purpose of hiding, the creature is heavily obscured. The creature’s location can be detected by any noise it makes or any tracks it leaves.

Attack rolls against the creature have disadvantage, and the creature’s attack rolls have advantage.');
INSERT INTO conditions (name, description) VALUES ('Paralyzed', 'A paralyzed creature is incapacitated (see the condition) and can’t move or speak.

The creature automatically fails Strength and Dexterity saving throws.

Attack rolls against the creature have advantage.

Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.');
INSERT INTO conditions (name, description) VALUES ('Petrified', 'A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.

The creature is incapacitated (see the condition), can’t move or speak, and is unaware of its surroundings.

Attack rolls against the creature have advantage.

The creature automatically fails Strength and Dexterity saving throws.

The creature has resistance to all damage.

The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized.');
INSERT INTO conditions (name, description) VALUES ('Poisoned', 'A poisoned creature has disadvantage on attack rolls and ability checks.');
INSERT INTO conditions (name, description) VALUES ('Prone', 'A prone creature’s only movement option is to crawl, unless it stands up and thereby ends the condition.

The creature has disadvantage on attack rolls.

An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.');
INSERT INTO conditions (name, description) VALUES ('Restrained', 'A restrained creature’s speed becomes 0, and it can’t benefit from any bonus to its speed.

Attack rolls against the creature have advantage, and the creature’s attack rolls have disadvantage.

The creature has disadvantage on Dexterity saving throws.');
INSERT INTO conditions (name, description) VALUES ('Stunned', 'A stunned creature is incapacitated (see the condition), can’t move, and can speak only falteringly.

The creature automatically fails Strength and Dexterity saving throws.

Attack rolls against the creature have advantage.');
INSERT INTO conditions (name, description) VALUES ('Unconscious', 'An unconscious creature is incapacitated (see the condition), can’t move or speak, and is unaware of its surroundings

The creature drops whatever it’s holding and falls prone.

The creature automatically fails Strength and Dexterity saving throws.

Attack rolls against the creature have advantage.

Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.');

-- backgrounds ------------------------------------------------------------
INSERT INTO backgrounds (name, description, skill_proficiencies, tool_proficiencies, bonus_language_count, equipment_text, feature_name, feature_description) VALUES ('Acolyte', 'You have spent your life in the service of a temple to a specific god or pantheon of gods. You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine. You are not necessarily a cleric—performing sacred rites is not the same thing as channeling divine power.

Choose a god, a pantheon of gods, or some other quasi-divine being from among those listed in "Fantasy-Historical Pantheons" or those specified by your GM, and work with your GM to detail the nature of your religious service. Were you a lesser functionary in a temple, raised from childhood to assist the priests in the sacred rites? Or were you a high priest who suddenly experienced a call to serve your god in a different way? Perhaps you were the leader of a small cult outside of any established temple structure, or even an occult group that served a fiendish master that you now deny.', 'Insight, Religion', NULL, 2, 'A holy symbol (a gift to you when you entered the priesthood), a prayer book or prayer wheel, 5 sticks of incense, vestments, a set of common clothes, and a pouch containing 15 gp', 'Shelter of the Faithful', 'As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity. You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle.

You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there. This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home. While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple.');
